#!/usr/bin/env node

/**
 * Generate Dart environment configuration from Vercel environment variables
 * This script runs during Vercel build to inject env vars as compile-time constants
 */

const fs = require('fs');
const path = require('path');

// Read environment variables
const envVars = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
  TMDB_API_KEY: process.env.TMDB_API_KEY || '',
  TMDB_BASE_URL: process.env.TMDB_BASE_URL || 'https://api.themoviedb.org/3',
  TMDB_IMAGE_BASE: process.env.TMDB_IMAGE_BASE || 'https://image.tmdb.org/t/p/w500',
};

// Validate required variables
const required = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'TMDB_API_KEY'];
const missing = required.filter(key => !envVars[key]);

if (missing.length > 0) {
  console.error('❌ Missing required environment variables:', missing.join(', '));
  process.exit(1);
}

// Generate Dart file content
const dartContent = `// GENERATED FILE - DO NOT EDIT
// Generated by generate_env.js during build
// Source: Vercel environment variables

// Supabase
const String _supabaseUrl = '${envVars.SUPABASE_URL}';
const String _supabaseAnonKey = '${envVars.SUPABASE_ANON_KEY}';

// TMDB
const String _tmdbApiKey = '${envVars.TMDB_API_KEY}';
const String _tmdbBaseUrl = '${envVars.TMDB_BASE_URL}';
const String _tmdbImageBase = '${envVars.TMDB_IMAGE_BASE}';

// Getters for platform-agnostic access
String getSupabaseUrl() => _supabaseUrl;
String getSupabaseAnonKey() => _supabaseAnonKey;
String getTmdbApiKey() => _tmdbApiKey;
String getTmdbBaseUrl() => _tmdbBaseUrl;
String getTmdbImageBase() => _tmdbImageBase;

Future<void> initEnv() async {
  // No initialization needed for web - values are compile-time constants
}

bool validateEnv() {
  return _supabaseUrl.isNotEmpty &&
      _supabaseAnonKey.isNotEmpty &&
      _tmdbApiKey.isNotEmpty;
}
`;

// Write to file
const outputPath = path.join(__dirname, 'lib', 'core', 'config', 'env_config_web.dart');
fs.writeFileSync(outputPath, dartContent, 'utf8');

console.log('✅ Generated env_config_web.dart successfully');
console.log('   SUPABASE_URL:', envVars.SUPABASE_URL ? '✓' : '✗');
console.log('   SUPABASE_ANON_KEY:', envVars.SUPABASE_ANON_KEY ? '✓' : '✗');
console.log('   TMDB_API_KEY:', envVars.TMDB_API_KEY ? '✓' : '✗');
